networks:
  stack:
    name: stack
    driver: bridge



services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - N8N_HOST=${N8N_DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${N8N_DOMAIN}
      - N8N_SECURE_COOKIE=true
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - EXECUTIONS_MODE=${EXECUTIONS_MODE}
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=mariadb
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=${MARIADB_DATABASE}
      - DB_MYSQLDB_USER=${MARIADB_USER}
      - DB_MYSQLDB_PASSWORD=${MARIADB_PASSWORD}
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - stack
    # 本机直连（仅回环），例如 http://127.0.0.1:5678
    # 注意：若保持 N8N_SECURE_COOKIE=true，本机用 HTTP 登录会失败（见下方说明）
    ports:
      - "127.0.0.1:5678:5678"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      sh -c 'echo 1 > /proc/sys/vm/overcommit_memory &&
      redis-server
      --save 20 1
      --loglevel warning
      --requirepass "$$REDIS_PASSWORD"'
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    networks:
      - stack
    # 本机直连 redis-cli -h 127.0.0.1 -p 6379 -a $REDIS_PASSWORD
    ports:
      - "127.0.0.1:6379:6379"
    # 添加特权模式以允许修改系统参数
    privileged: true

  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - stack
    # 本机直连 MariaDB: mysql -h 127.0.0.1 -P 3306 -u ${MARIADB_USER} -p
    ports:
      - "127.0.0.1:3306:3306"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    depends_on:
      - n8n
    networks:
      - stack
